apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: yb7kazw97-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/yb7kazw97-dotnet-basic-gitops